name: dog-classifier
channels:
- anaconda-fusion
- defaults
dependencies:
- alabaster=0.7.10=py35_0
- babel=2.5.0=py35_0
- click=6.7=py35_0
- cycler=0.10.0=py35_0
- docutils=0.14=py35_0
- flask=0.12=py35_0
- flask-cors=3.0.2=py35_0
- freetype=2.5.5=2
- h5py=2.6.0=np112py35_2
- hdf5=1.8.17=2
- icu=54.1=0
- imagesize=0.7.1=py35_0
- itsdangerous=0.24=py35_0
- jbig=2.1=0
- jinja2=2.9.6=py35_0
- jpeg=9b=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- markupsafe=1.0=py35_0
- matplotlib=2.0.2=np112py35_0
- mkl=2017.0.3=0
- numpy=1.12.0=py35_0
- numpydoc=0.6.0=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2l=0
- pillow=4.0.0=py35_1
- pip=9.0.1=py35_1
- pygments=2.2.0=py35_0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.3=1
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2=2
- readline=6.2=2
- requests=2.14.2=py35_0
- scikit-learn=0.18.1=np112py35_1
- scipy=0.19.0=np112py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.6.3=py35_0
- sphinxcontrib=1.0=py35_0
- sphinxcontrib-websupport=1.0.1=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.12=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - gunicorn==19.7.1
  - keras==2.0.8
  - opencv-python==3.2.0.6
  - protobuf==3.4.0
  - pyyaml==3.12
  - tensorflow==1.0.0
  - tensorflow-gpu==1.1.0
